import * as React from 'react'
import 'zenticons/lib/index.css'
import classnames from 'classnames'
export type IconProps = {
  type: string,
  className?: string
}
// using zent icons
/* auto-generate: start */
export type IconType =
  | 'approval'
  | 'approval-o'
  | 'arrow-down'
  | 'arrow-up'
  | 'assess'
  | 'assess-o'
  | 'bell'
  | 'bell-o'
  | 'business'
  | 'business-o'
  | 'calendar'
  | 'calendar-o'
  | 'capital'
  | 'capital-o'
  | 'caret-down'
  | 'caret-up'
  | 'casher'
  | 'channel-o'
  | 'chart'
  | 'chart-o'
  | 'check'
  | 'check-circle'
  | 'check-circle-o'
  | 'checkin'
  | 'checkin-o'
  | 'clock'
  | 'clock-o'
  | 'close'
  | 'close-circle'
  | 'close-circle-o'
  | 'contract-o'
  | 'countdown'
  | 'customer'
  | 'customer-o'
  | 'customer-service'
  | 'download'
  | 'edit-o'
  | 'error-circle'
  | 'error-circle-o'
  | 'expand-customer'
  | 'expand-customer-o'
  | 'export'
  | 'feedback'
  | 'flow-o'
  | 'forbidden-circle'
  | 'gift'
  | 'goods'
  | 'goods-o'
  | 'hc-manage'
  | 'hc-manage-o'
  | 'help-circle'
  | 'help-circle-o'
  | 'hotline-o'
  | 'hr'
  | 'hr-o'
  | 'im-o'
  | 'info-circle'
  | 'info-circle-o'
  | 'knowledge-o'
  | 'lock'
  | 'marketing'
  | 'message'
  | 'message-o'
  | 'order'
  | 'order-o'
  | 'pending-circle'
  | 'plus'
  | 'plus-circle-o'
  | 'qa-o'
  | 'remove-o'
  | 'report'
  | 'report-o'
  | 'right'
  | 'right-circle'
  | 'rights-list-o'
  | 'search'
  | 'settings'
  | 'settings-o'
  | 'share'
  | 'shop'
  | 'shop-decorate'
  | 'shop-o'
  | 'shop-template'
  | 'star'
  | 'star-o'
  | 'strategy-o'
  | 'subtract-circle-o'
  | 'suggestions'
  | 'summary'
  | 'summary-o'
  | 'text-guide'
  | 'ticket'
  | 'ticket-o'
  | 'tools-o'
  | 'unlock'
  | 'upload'
  | 'video-guide'
  | 'visit-o'
  | 'warning'
  | 'warning-o'
  | 'youzan'
  | 'youzan-o';
/* auto-generate: end */

export default class extends React.Component<IconProps> {
  constructor(props: IconProps) {
    super(props)
  }


  render() {
    const { type, className, ...otherProps } = this.props;
    const cls = classnames('zenticon', `zenticon-${type}`, className);

    return <i className={cls} {...otherProps} />;
  }
}